display: Adjust maximum allowed resolution
DragonMinded/libdragon pull request #396
Opened 2023-07-08 21:38 UTC by sp1187

2023-07-10 14:53 UTC, rasky requested changes
Thanks! See the comments below.

2023-07-10 14:53 UTC, rasky commented on src/display.c
> +    assertf(res.width < 1024, "widths >= 1024 are not supported by RDP");
I don't think we should limit display size because of RDP constraints. There can be various tricks to workaround this restriction.

I would keep here the physical limit (whatever that is), and then add an assert to `rdp_attach` on trunk and `rdpq_set_color_image_raw` on unstable that verifies that the width / stride isn't bigger than 1024.

2023-08-18 21:54 UTC, sp1187 commented
Finding the maximum non-buggy horizontal resolution turned out to be more complex as it depends on bandwidth usage on real hardware, which is affected by the color depth and anti-aliasing mode used. Therefore I removed the vertical resolution change as more investigation is needed there.

2023-08-18 22:06 UTC, merged

2023-08-18 22:06 UTC, rasky commented
Thanks